# Generated by Django 5.0.2 on 2024-02-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_rename_amount_coffeepurchase_cost_userdebtsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeepurchase',
            name='date_purchased',
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
