# Generated by Django 5.0.2 on 2024-02-16 23:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_remove_coffeepurchase_date_purchased_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeepurchase',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='date_purchased',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Enter the cost of the coffee', max_digits=6),
        ),
    ]
